AllCops:
  NewCops: enable
  Exclude:
    - bin/bundle
    - db/schema.rb
    - test/test_helper.rb
    - db/migrate/*

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false