version: '3.8'
services:
  db:
    env_file: .env
    image: postgres
    volumes:
      - postgres-store:/var/lib/postgresql/data
  web:
    build: .
    command: bash -c "yarn install && yarn build && yarn build:css && rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file: .env
    environment:
      RAILS_ENV: development
      RAILS_MAX_THREADS: 5
volumes:
  postgres-store:
